---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: apicart
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: apicart
  minReplicas: 6
  maxReplicas: 20
  targetCPUUtilizationPercentage: 75
